# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 935c8cc384f172a461f650820443e63304e0761f2305632e2b06e929c6d7ac4e0b91418e3c1c73d0ea477a6b9a136986f83519cfd889758e9b19c955effe5cc3

test:
  secret_key_base: a82800d9c2dacd5d63464c3f9a7072d0d2ee97a38b92af7d6492a9e20716129a274c31f8520ec234bcdce0828921d587d08d97a9c86175e1132ec4f9c5d0284a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
